### ISSUE TITLE
Laptop Interface Missing

### ISSUE THREAD

**Issue by kobe-maru** [linuxgurugamer/MemGraph#1]
Many laptops do not have access to the numpad keys, meaning the mod window cannot be hidden without an external keyboard.

**Comment by linuxgurugamer** [comment]
Most laptops I've seen have a virtual numpad if they don't have a real one.  Usually accessed by a Fn key.

Please check to see if your laptop has one, and if so, test to see if it works.

I'm not discounting this, but need to prioritize my work.

**Comment by kobe-maru** [comment]
Unless that is a windows feature I am unaware of, I've never had a laptop with that ability. My current laptop certainly does not.

**Comment by linuxgurugamer** [comment]
It's hardware, not Windows.
I'll see what I can do

**Comment by linuxgurugamer** [comment]
An 'X' button to close the window has been added at the top right
